sudo: false

language: python
python: "2.7"

env:
    global:
        ANSIBLE_CONFIG: tests/ansible.cfg

install:
    - pip install ansible

before_script:
    - ansible-galaxy install -r roles.txt

script:
    - ansible-playbook -i tests/inventory --syntax-check playbook.yml
    - ansible-playbook -i tests/inventory --connection=local --check playbook.yml

addons:
    apt:
        packages:
            - python-apt
            - python-pycurl
