sudo: required

language: python
python: "2.7"

install:
    - sudo pip install ansible

before_script:
    - sudo ansible-galaxy install -r roles.txt

script:
    - ansible-playbook -i production --check playbook.yml

addons:
    apt:
        packages:
            - python-apt
            - python-pycurl
