- hosts: minecraft
  var_files:
      - vars/players.yml
  roles:
       - role: kamaln7.swapfile
         swapfile_size: 1GB
         swapfile_swappiness: 10
         swapfile_location: /mnt/swapfile
       - role: benwebber.minecraft
         minecraft_version: "1.11"
         minecraft_whitelist: {{ whitelist }}
         minecraft_ops: {{ ops }}
         minecraft_process_control: "supervisor"
         minecraft_initial_memory: 512M
